server:
  port: 8080
  servlet:
    # context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1004392362360-b4bepp13vqhaomhc1jm040ohveuoe6mu.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true